name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Show SSH key fingerprint
        run: |
          ssh-add -l

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH
        run: |
          ssh celliersaintvincent@${{ secrets.SSH_HOST }} "whoami"

      - name: Deploy
        run: |
          ssh deploy@${{ secrets.SSH_HOST }} "
            cd /home/celliersaintvincent &&
            git pull &&
            php artisan migrate --force
          "
